services:
  - type: web
    name: autismcure
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: ADMIN_USERNAME
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      - key: DATABASE_PATH
        value: /var/data/autism_cure.db
    disk:
      name: autism-cure-data
      mountPath: /var/data
      sizeGB: 1
